
<HTML>
    <HEAD> <TITLE>Consulta</TITLE> </HEAD>
    
    <BODY>   

        <form name="formulario" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
            <fieldset style="width: 300px; padding:25px; margin:50px">
    
           <h1>Login</h1>
    
            CustomerNumber <input type="text" name="CustomerNumber">
            <br><br>
            ContactLastName <input type="password" name="ContactLastName">
            <br><br>
            <input type="submit" name="Enviar" value="Iniciar Sesion">
            <input type="reset" name="Borrar" value="Borrar">
        </fieldset>
        
            </form>	
    
           
            <?php






?>

    </BODY>
    </HTML>
